# TODO: change and use parser instead
# TODO: create 2 files, one for multi and one for univariate case
MULTI: True

MULTIVARIATE:
  # TODO: add field 'ALGORITHM'
  PREPROCESSING_PARAMS:
    'downsamplig_rate': 5
    'window_size': 12
    'normalization': 'all'
    'metrics': 'columns_6'  # accept a list of columns [metric1, metric2, ...]
    'multi_file' : False  # if data is already divided in Train and Test data

  TRAINING_PARAMS:
    'batch_size': 32
    'epochs': 3
    'hidden_size': 10
    'alpha': 0.5
    'beta': 0.5

  INTERVALS_PARAMS:
    'train_start': 40320
    'train_end': 70560
    'test_start': 0
    'test_end': 30240

  TH_ALGORITHM: 'iqr'
  DF_PATH: "/notebooks/anomaly-detector/data/raw/V_GV_SYSMETRIC_INCTANCE_2.csv"
  
  PLOT_PARAMS:
    'history_static': True
    'history_html': False
    'db_time_static': True
    'db_time_html': False
    'labels_static': True
    'labels_html': False
    'thresholds_static' : True
    'thresholds_html' : True

UNIVARIATE:
  ALGORITHM: 'knn'

  PREPROCESSING_PARAMS:
    'downsamplig_rate': 5
    'normalization': null  # z-score, min-max, all, null
    'metric': [ 'Database Time Per Sec' ]

  TRAINING_PARAMS:
    'contamination': 0.001

  INTERVALS_PARAMS:
    'start': 0
    'end': 30240

  TH_ALGORITHM: 'iqr'
  DF_PATH: "/notebooks/anomaly-detector/data/raw/V_GV_SYSMETRIC_INCTANCE_2.csv"
  
  PLOT_PARAMS:
    'db_time_static': True
    'db_time_html': False
    'labels_static': True
    'labels_html': False
    